### ISSUE TITLE
systemd: Error loading unit file: `system.Error.ENOEXEC`

### ISSUE THREAD

**Issue by dx0x58** [papanito/ansible-role-cloudflared#40]
Hey! I have a playbook that looks like this:
```
---
- hosts: redash
  become: yes
  remote_user: ubuntu
  vars:
    cf_cert_content: "{{ vault_redash_cf_tunnel_cert }}"
    cf_tunnels:
      redash:
        account_tag: "{{ vault_redash_cf_tunnel_account_tag }}"
        tunnel_secret: "{{ vault_redash_cf_tunnel_secret }}"
        tunnel_id: "{{ vault_redash_cf_tunnel_id }}"
        routes:
          dns:
          - "redash.internal"
        ingress:
        - hostname: "redash.internal.mydomain.com"
          service: http://localhost:80 # redash local webserver
  roles:
    - redash
  roles:
    - papanito.cloudflared
```

and after running I get the error:

<img width="1440" alt="CleanShot 2021-12-01 at 19 29 15@2x" src="https://user-images.githubusercontent.com/3293970/144273548-249e138c-021a-48a1-bd9f-6ce831c8c82b.png">

Is this line the problem ? 
https://github.com/papanito/ansible-role-cloudflared/blob/0f55bb79322176f6b218c864b5a62c8227b5815e/tasks/configure_systemd.yml#L8

 Perhaps we need to use the name of the service here (like `dest: "{{ cf_systemd_target_dir }}/{{ systemd_filename }}@ {{ **cf_tunnel.key** }}.service"`)?

There is only `cloudflared@.service` file on my server, but not `cloudflared@redash` as expected
