### ISSUE TITLE
cf_ssh_client_config_group does not seem to be respected

### ISSUE THREAD

**Issue by timatlee** [papanito/ansible-role-cloudflared#65]
When following https://github.com/papanito/ansible-role-cloudflared#ssh-client-config, it says to define `cf_ssh_client_config_group` to be the group that your servers are in. This doesn't seem to work - the playbook seems to statically reference the `servers` group.

Error I'm getting:
```
TASK [papanito.cloudflared : Add ssh proxy for all servers in the ssh client config] ***************************************************************************************
fatal: [cftunnel]: FAILED! => {"msg": "'dict object' has no attribute 'servers'. 'dict object' has no attribute 'servers'"}
```

If I name my group the expected `servers`, the playbook executes.

In `main.yml', around line 101, I see:
```
- name: Add ssh proxy for all servers in the ssh client config
  include_tasks:
    file: ssh_client_config.yml
    apply:
      tags: cf_client_config
  loop: "{{ groups['servers'] }}"
  when: cf_ssh_client_config
  tags:
  - cf_client_config
```

By changing `  loop: "{{ groups['servers'] }}"` to `  loop: "{{ groups[cf_ssh_client_config_group] }}"`, the playbook works as expected - but I'm not sure what knockoff issues that may have.
